PROCESS-NAME,ai.character.app
PROCESS-NAME,ai.liquid.chatapp
PROCESS-NAME,ai.perplexity.app.android
PROCESS-NAME,ai.x.grok
PROCESS-NAME,au.com.shiftyjelly.pocketcasts
PROCESS-NAME,com.android.vending
PROCESS-NAME,com.binance.dev
PROCESS-NAME,com.delphicoder.flud.paid
PROCESS-NAME,com.discord
PROCESS-NAME,com.duolingo
PROCESS-NAME,com.follow.clash
PROCESS-NAME,com.getsurfboard
PROCESS-NAME,com.github.android
PROCESS-NAME,com.google.android.accessibility.reader
PROCESS-NAME,com.google.android.apps.authenticator2
PROCESS-NAME,com.google.android.apps.bard
PROCESS-NAME,com.google.android.apps.docs
PROCESS-NAME,com.google.android.apps.googlevoice
PROCESS-NAME,com.google.android.apps.healthdata
PROCESS-NAME,com.google.android.apps.labs.language.tailwind
PROCESS-NAME,com.google.android.apps.subscriptions.red
PROCESS-NAME,com.google.android.configupdater
PROCESS-NAME,com.google.android.documentsui
PROCESS-NAME,com.google.android.ext.services
PROCESS-NAME,com.google.android.ext.shared
PROCESS-NAME,com.google.android.gm
PROCESS-NAME,com.google.android.gms
PROCESS-NAME,com.google.android.gms.location.history
PROCESS-NAME,com.google.android.googlequicksearchbox
PROCESS-NAME,com.google.android.gsf
PROCESS-NAME,com.google.android.keep
PROCESS-NAME,com.google.android.onetimeinitializer
PROCESS-NAME,com.google.android.printservice.recommendation
PROCESS-NAME,com.google.android.syncadapters.contacts
PROCESS-NAME,com.google.android.tts
PROCESS-NAME,com.google.android.youtube
PROCESS-NAME,com.google.ar.core
PROCESS-NAME,com.innologica.inoreader
PROCESS-NAME,com.instagram.android
PROCESS-NAME,com.javdb.javrocket
PROCESS-NAME,com.medium.reader
PROCESS-NAME,com.nebula.clashmi
PROCESS-NAME,com.openai.chatgpt
PROCESS-NAME,com.poe.android
PROCESS-NAME,com.reddit.frontpage
PROCESS-NAME,com.twitter.android
PROCESS-NAME,com.v2ray.ang
PROCESS-NAME,io.heckel.ntfy
PROCESS-NAME,is.follow
PROCESS-NAME,mob.play.rflx
PROCESS-NAME,mobi.beyondpod.unlockkey
PROCESS-NAME,org.telegram.messenger
PROCESS-NAME,tv.twitch.android.app
PROCESS-NAME,xxx.pornhub.fuck
PROCESS-NAME,xyz.blueskyweb.app
（内容由AI生成，仅供参考）
